FROM python:3.9-slim

# Checkout and install dagster libraries needed to run the gRPC server
# exposing your repository to dagit and dagster-daemon, and to load the DagsterInstance
RUN pip install --upgrade pip

RUN pip install \
    dagster \
    dagster-postgres \
    dagster-docker

# Add repository code
ENV APP_DIR /opt/dagster/app

RUN mkdir -p $APP_DIR

WORKDIR $APP_DIR

COPY dag_dbt/repository.py ./
COPY requirements.txt ./
COPY . .

RUN pip install --no-cache-dir -r requirements.txt

# Run dagster gRPC server on port 4000

EXPOSE 4000

# CMD allows this to be overridden from run launchers or executors that want
# to run other commands against your repository
CMD ["dagster", "api", "grpc", "-h", "0.0.0.0", "-p", "4000", "-f", "repository.py"]