config:
    use_colors: True
dag_dbt_data:
  target: local
  outputs:
    local:
      type: postgres
      threads: 1
      host: 192.168.1.38
      port: 5432
      user: "myuser"
      pass: "mypass"
      dbname: demodb
      schema: public
      client_session_keep_alive: False
